version: "3"
services:
  db:
    build:
      context: .
      dockerfile: mssql.Dockerfile
    container_name: tib-db
    environment:      
      SA_PASSWORD: Somepassword#123
    networks:
      - tib
    ports:
      - "1433:1433"

  # tibtest:
  #   depends_on:
  #     - db
  #   build:
  #     context: ../
  #   environment:
  #     JDBC_URL: "jdbc:sqlserver://db:1433;databaseName=master;user=sa;password=Somepassword#123"


networks: 
  tib:
    driver: bridge

volumes:
  conns: